# POINTING_DEVICE_ENABLE = no
# POINTING_DEVICE_ENABLE = yes
# POINTING_DEVICE_DRIVER = cirque_pinnacle_i2c

CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes

DEBOUNCE_TYPE = asym_eager_defer_pk

OLED_ENABLE = no

WPM_ENABLE = no

RGBLIGHT_ENABLE = no
RGBLIGHT_DRIVER = ws2812
