// Copyright 2022 saikocat (@saikocat)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#undef EE_HANDS

#define TAPPING_TERM 175

#define DEBUG_MATRIX_SCAN_RATE

/* Mod tap settings */
#define PERMISSIVE_HOLD_PER_KEY
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#define TAPPING_FORCE_HOLD_PER_KEY

/* OLED */
// #define OLED_DISABLE_TIMEOUT
#define OLED_IDLE_THRESHOLD 30000U
#define SPLIT_OLED_ENABLE

/* One Shot */
#define ONESHOT_TIMEOUT 3000
#define ONESHOT_TAP_TOGGLE 3

/* Combo */
#if defined(COMBO_ENABLE)
#    define COMBO_TERM 25
#    define COMBO_ONLY_FROM_LAYER 0
#endif

/* Caps Word */
#if defined(CAPS_WORD_ENABLE)
#    define CAPS_WORD_IDLE_TIMEOUT 3000
//#    define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
#    define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#endif

/* Pointing Device: Cirque Trackpad */
#define SPLIT_POINTING_ENABLE

#define POINTING_DEVICE_RIGHT
#define POINTING_DEVICE_ROTATION_90
#define POINTING_DEVICE_INVERT_X
#define POINTING_DEVICE_INVERT_Y
#define POINTING_DEVICE_TASK_THROTTLE_MS 10
#define POINTING_DEVICE_GESTURES_SCROLL_ENABLE
#define POINTING_DEVICE_GESTURES_CURSOR_GLIDE_ENABLE

#define CIRQUE_PINNACLE_DIAMETER_MM 35
#define CIRQUE_PINNACLE_POSITION_MODE CIRQUE_PINNACLE_ABSOLUTE_MODE
#define CIRQUE_PINNACLE_TAP_ENABLE

/* Split Data Sync Options */
#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_MODS_ENABLE
// #define SPLIT_TRANSPORT_MIRROR
// #define SPLIT_LED_STATE_ENABLE
#define SPLIT_WPM_ENABLE
